### ISSUE TITLE
Yields different results if a structs field is a pointer vs. value

### ISSUE THREAD

**Issue by dionysius** [InVisionApp/conjungo#23]
https://play.golang.org/p/mgcKU7YcxX1

That also results to the custom type merge function not beeing called.

I debugged it until https://github.com/InVisionApp/conjungo/blob/master/mfunc.go#L60. Where `v.Type()` is `Ptr`, and it can't find a default merge function for that kind, since there's none.

So it continues and uses https://github.com/InVisionApp/conjungo/blob/master/mfunc.go#L80 which just replaces the whole tree without deep merging further

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
